# Generated by Django 5.2.7 on 2025-11-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForoProyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
