# Generated by Django 5.2.7 on 2025-11-06 07:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForoProyectos', '0002_pregunta_foto_respuesta_foto_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='ForoProyectos.usuario'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='ForoProyectos.usuario'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='ForoProyectos.pregunta'),
        ),
    ]
