# Generated by Django 5.2.7 on 2025-11-06 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForoProyectos', '0003_respuesta_fecha_publicacion_alter_pregunta_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_autor', to='ForoProyectos.usuario'),
        ),
    ]
